USE ingevora;

ALTER TABLE payments
  MODIFY COLUMN stripe_session_id VARCHAR(255) NULL,
  ADD COLUMN payment_method ENUM('CARD', 'COD') NOT NULL DEFAULT 'CARD' AFTER service_request_id,
  MODIFY COLUMN status ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'COD_PENDING') NOT NULL DEFAULT 'PENDING';

ALTER TABLE service_requests
  MODIFY COLUMN payment_status ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'COD_PENDING') NOT NULL DEFAULT 'PENDING';
